apiVersion: apps/v1
kind: Deployment
metadata:
  name: code-deployment
  labels:
    app: code
spec:
  replicas: 1
  selector:
    matchLabels:
      app: code
  template:
    metadata:
      labels:
        app: code
    spec:
      containers:
      - name: code
        image: vincentstrife/codeservertest:latest
        ports:
        - containerPort: 9091