apiVersion: v1
kind: Service
metadata:
  name: code-service
  labels:
    app: code
spec:
  type: NodePort
  ports:
  - port: 9091
    protocol: TCP
    nodePort: 30000
  selector:
    app: code