apiVersion: v1
kind: Service
metadata:
  name: kafka-service ## name of the Service
spec:
  type: ClusterIP
  selector:
    app: kafka ## Serves as a label which should be refrenced in a Pod / Deployment manifest file
  ## department: ##same as above
  ports:
  - protocol: TCP ##The default is TCP
    port: 9092